### ISSUE TITLE
No release 

### ISSUE THREAD

**Issue by AnonymeDuScript** [Zekiah-A/RplaceServer#2]
Hi 
I don't view any release about the RplaceServer it normal ?

**Comment by Zekiah-A** [comment]
> Hi I don't view any release about the RplaceServer it normal ?
Sorry I just didn't have time to make a release, I am working on something that will allow anyone to really quickly spin up a server, without even having to touch this github at all, in the meantime, you can use dotnet to run TKOfficial (the console server software) here
