### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Outfit8TSB** [Zekiah-A/RplaceServer#7]
Unhandled exception. (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 10, Idx: 9): Property 'cert_path' not found on type 'TKOfficial.Config'.

i have to run it to prepare for January 1st 2025 event(see rslashplace2/rslashplace2.github.io#355 for 1.1.2025 event)!

**Comment by Zekiah-A** [comment]
I am currently updating this server software to work better, this included some changes to how config files are processed. Are you building the latest version of the code from source, or using one of the releases?

**Comment by Outfit8TSB** [comment]
One of the releases.

**Comment by Outfit8TSB** [comment]
so i knew that releases version is not working so
i used dotnet run instead.
but after i access to it using the https://rplace.live/?server=wss://2406-5900-102c-49d-6139-8e1f-facd-136d.sslip.io:8080&board=https://2406-5900-102c-49d-6139-8e1f-facd-136d.sslip.io:8081/place it doesn't work.

**Comment by Outfit8TSB** [comment]
but still solved, and the https://rplace.live/?server=wss://2406-5900-102c-49d-6139-8e1f-facd-136d.sslip.io:8080&board=https://2406-5900-102c-49d-6139-8e1f-facd-136d.sslip.io:8081/place issue will transfer to #8
